### ISSUE TITLE
Server Hosted

### ISSUE THREAD

**Issue by JamesPierce82** [MAD-Club/RinsedBot#1]
We should get this set up on Nick's server if possible so that we can keep it running.

**Comment by j-nguyen** [comment]
I think you can either use supervisor, creating a service in Ubuntu, or to use the `forever` script that runs the script "forever".

I think our best bet would be to use supervisor/service ubuntu so we can start/stop anytime we want

**Comment by JamesPierce82** [comment]
Supervisor looks like it should do a lot of what we would need. It would also be useful so that if we have other scripts running in the future we can manage them in one place.

**Comment by JamesPierce82** [comment]
Since this is now running on the server, I think we are good to close this, although I do have a question about deployment on the server.

I had discussed with Brandon possible ways to automatically restart the bot when master is updated to make it easier to deal with updating code, although the examples he showed me were in Ruby. I assume we will probably need to implement something for this as well.

The other thing I noticed is that the server version has some changes not pushed to github. Is there anything there we need to push straight to master?

**Comment by j-nguyen** [comment]
Oh, is he talking about capistrano? We can still do that way if you'd like.

**Comment by JamesPierce82** [comment]
I believe it was. I don't know enough about deployment to know what options there are, so if Capistrano will do what we need, I'm down to use that.

**Comment by j-nguyen** [comment]
It feels a bit odd deploying Node.js applications using Capistrano, a ruby type environment however. Let me see if there's any alternatives, before using Capistrano.

**Comment by j-nguyen** [comment]
After searching, there's this https://github.com/shipitjs/shipit that similarly deploys much like capistrano
